auth/urls.py
from django.conf.urls import patterns, url
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
    url(r'^login/$', 'auth.views.login', name='login'),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
    url(r'^success/$', lambda x: HttpResponseRedirect('/md/'), name='success'),

    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'auth/password_reset_confirm.html',
        'post_reset_redirect' : '/auth/password/reset/complete/'},
        name='password_reset_confirm'),

    url(r'^password/reset/complete/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'auth/password_reset_complete.html'},
        name='password_reset_complete'),

    url(r'^$', lambda x: HttpResponseRedirect('login/')),
)

maildude/urls.py
from django.conf.urls import patterns, include, url
from django.http import HttpResponseRedirect

urlpatterns = patterns('',
    url(r'^$', lambda x: HttpResponseRedirect('auth/')),
    url(r'^auth/', include('auth.urls', namespace="auth")),
    url(r'^md/', include('md.urls', namespace="md")),
)

md/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.http import HttpResponseRedirect

urlpatterns = patterns('md.views',
    url(r'^$', 'dashboard.index', name='dashboard'),

    # CAMPAIGNS ##############################################
    url(r'^campaigns/$', 'campaigns.index', name='campaigns_page'),

    # TEMPLATES ##############################################
    url(r'^templates/$', 'templates.index', name='templates_page'),

    # LISTS ##############################################
    url(r'^lists/$', 'lists.index', name='lists_page'),

    # MY ACCOUNT #########################################
    url(r'^get-part/$', 'account.get_part', name='account_get_part'),
    url(r'^get-form/$', 'account.get_form', name='account_get_form'),
    url(r'^my-account/$', 'account.index', name='account_page'),
    url(r'^get-qr-code/$', 'account.get_QR_code', name='get_qr_code'),
    url(r'^get-totp-current-value/$', 'account.get_TOTP_current_value', name='get_totp_current_value'),
    url(r'^set-otp-key/$', 'account.set_otp_key', name='set_otp_key'),
    url(r'^cancel-otp-check/$', 'account.cancel_otp_check', name='cancel_otp_check'),

    url(r'^$', lambda x: HttpResponseRedirect('/')),
)

md/models/smtp_account.py
# -*- coding: utf-8 -*-

from django.db import models


class SmtpAccountModel(models.Model):
    account_name = models.CharField(max_length=128, db_index=True, unique=True)
    host = models.CharField(max_length=128)
    port = models.CharField(max_length=5, default='25')
    username = models.CharField(max_length=128)
    password = models.DateTimeField(auto_now_add = True, db_index = True)

    def __unicode__(self):
        return u"{0} {1}:{2} ({3)".format(self.account_name, self.host, self.port, self.username)

    def export(self):
        return [()]

    class Meta:
        # ordering = ["-created"]
        app_label = 'md'

md/forms/smtp_account.py
# -*- coding: utf-8 -*-

#
#   SMTP ACCOUNT FORM
#

from django import forms
from django.utils.translation import ugettext as _

from md.models.smtp_account import SmtpAccountModel
from md.regexp import get_dojo_validator, get_form_validator


class SmtpAccountForm(forms.ModelForm):
    account_name = forms.CharField(
        label=_("Account Name"),
        required=True,
        max_length=128,
        widget=forms.TextInput(attrs={
            'trim': 'true',
            'data-dojo-type': 'md/iValidationTextBox',
            'data-dojo-props': "required: true, pattern: '%s'" % get_dojo_validator('name'),
            #'validator': 'list_name_validator',
            'invalidMessage': _("Invalid account name."),
            'promptMessage': _("Account name should be unique and representative.")
        }),
        validators=[get_form_validator('name')]
    )

    host = forms.CharField(
        label=_("Host"),
        required=True,
        max_length=128,
        widget=forms.TextInput(attrs={
            'trim': 'true',
            'data-dojo-type': 'md/iValidationTextBox',
            #'data-dojo-props': "required: true, pattern: '%s'" % dojo_regex_name(),
            #'validator': 'list_name_validator',
            'invalidMessage': _("Invalid host name."),
            'promptMessage': _("Host name or IP.")
        }),
    )

    port = forms.CharField(
        label=_("Port"),
        required=True,
        max_length=5,
        widget=forms.TextInput(attrs={
            'trim': 'true',
            'data-dojo-type': 'md/iValidationTextBox',
            #'data-dojo-props': "required: true, pattern: '%s'" % dojo_regex_name(),
            #'validator': 'list_name_validator',
            'invalidMessage': _("Invalid port."),
            'promptMessage': _("Used port for SMTP. It could be 25, 465, 587.")
        }),
    )

    username = forms.CharField(
        label=_("Username"),
        required=False,
        max_length=128,
        widget=forms.TextInput(attrs={
            'trim': 'true',
            'data-dojo-type': 'md/iValidationTextBox',
            #'data-dojo-props': "required: true, pattern: '%s'" % dojo_regex_name(),
            #'validator': 'list_name_validator',
            'invalidMessage': _("Invalid username"),
            'promptMessage': _("Username used for authentication.")
        }),
    )

    '''password = forms.CharField(
        label=_("Password"),
        required=False,
        max_length=128,
        widget=forms.TextInput(attrs={
            'trim': 'true',
            'data-dojo-type': 'md/iValidationTextBox',
            #'data-dojo-props': "required: true, pattern: '%s'" % dojo_regex_name(),
            #'validator': 'list_name_validator',
            'invalidMessage': '',
            'promptMessage': _("Password used for authentication.")
        }),
    )'''

    class Meta:
        model = SmtpAccountModel
        exclude = ['created']

md/views/account.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from pyotp import TOTP

from decorators import request_is_ajax
from md.helpers.account_helpers import generate_qrcode
from md.helpers.forms_factory import FormsFactory

from auth.models import AuthUser


def index(request):
    template_data = {}

    return render_to_response(
        'md/account.html', template_data,
        context_instance=RequestContext(request)
    )


def get_part(request):
    part_name = request.GET.get('partname', '')

    return render_to_response(
        'md/parts/' + part_name + '.html',
        {},
        context_instance=RequestContext(request)
    )


def get_form(request):
    form_name = request.GET.get('formname', '')

    template, template_data = FormsFactory.factory(form_name)

    return render_to_response(
        template,
        template_data,
        context_instance=RequestContext(request)
    )





@request_is_ajax
def get_QR_code(request):
    otp_image, otp_key = generate_qrcode(email_address=request.user.email)
    request.session['generated_otp_key'] = otp_key

    return HttpResponse(otp_image)


@request_is_ajax
def get_TOTP_current_value(request):
    otp_key = request.session.get('generated_otp_key', False)

    if otp_key:
        totp = TOTP(otp_key)
        resp = "%06d" % totp.now()
    else:
        resp = 0

    return HttpResponse(resp)


@request_is_ajax
def set_otp_key(request):
    otp_key = request.session.get('generated_otp_key', False)

    if otp_key:
        resp = AuthUser.objects.filter(pk=request.user.id).update(otp_token=otp_key)
        if resp:
            request.session['generated_otp_key'] = False
    else:
        resp = 0

    return HttpResponse(resp)


@request_is_ajax
def cancel_otp_check(request):
    AuthUser.objects.filter(pk=request.user.id).update(otp_token=None)

    return HttpResponse()

md/views/campaigns.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

#from md.forms.my_account import AuthUserForm

def index(request):
    template_data = {}

    #template_data['frm'] = AuthUserForm()
    return render_to_response('md/dashboard.html',
                              template_data,
                              context_instance=RequestContext(request))

md/views/dashboard.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

#from md.forms.my_account import AuthUserForm

def index(request):
    template_data = {}

    #template_data['frm'] = AuthUserForm()
    return render_to_response('md/dashboard.html',
                              template_data,
                              context_instance=RequestContext(request))

md/views/lists.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

def index(request):
    return render_to_response('md/lists.html', {},
                              context_instance=RequestContext(request))

md/views/templates.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

from django.http import HttpResponse
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

#from md.forms.my_account import AuthUserForm

def index(request):
    template_data = {}

    #template_data['frm'] = AuthUserForm()
    return render_to_response('md/dashboard.html',
                              template_data,
                              context_instance=RequestContext(request))

md/templates/md/account.html
{% extends 'md_base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block pagetitle %} {% trans "Account" %}{% endblock %}

{% block subsection_js %}
    <script src="{% static 'md/js/account.js' %}" type="text/javascript"></script>
{% endblock %}


{% block subsection_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'md/css/account.css' %}"
{% endblock %}


{% block maincontent %}
<div data-dojo-type="dijit/layout/TabContainer" class="tabs_container"  tabPosition="left-h" id="account_tab_container">
    <div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'Dashboard' %}" data-dojo-props="selected:true"
        id="tab_dashboard">
    </div>

    <div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'OTP Enrollment' %}" data-dojo-props="closable:false"
         id="tab_otp_enrollment">
    </div>


    <div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'Export Account' %}" data-dojo-props="closable:false"
        id="tab_export_settings">
    </div>


    <div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'SMTP Accounts' %}" data-dojo-props="selected:true"
        id="tab_smtp_settings">
    </div>
</div>
{% endblock %}

md/templates/md/campaigns.html
{% extends 'md_base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block pagetitle %} {% trans "Campaigns" %}{% endblock %}


{% block external_js %}
    <script src="{% static 'js/campaigns.js' %}" type="text/javascript"></script>
{% endblock %}

{% block maincontent %}
<div class="tabs_container">
	<div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 100%;" id="tab_campaigns"
		data-dojo-props="selected:true">

		<div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'Overview' %}"
			 id="tab_camps_tab1">

			<h4 id="camps_grid_message">{% trans 'Current Campaigns' %}</h4>
			<div id="current_camps_grid" style=""></div>

			<h4 id="camps_grid_message">{% trans 'Old Campaigns' %}</h4>
			<div id="old_camps_grid" style=""></div>
        </div>

		<div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'New Campaign' %}" id="tab_camps_tab2"
			href="{% url 'md:get_campaign_new_form' %}" refreshOnShow="true">
			{% comment %}
				The content is dynamically loaded from js
			{% endcomment %}
        </div>

	</div>
</div>

{% endblock %}

md/templates/md/dashboard.html
{% extends 'md_base.html' %}

{% load i18n %}
{% load url from future %}

{% block pagetitle %} {% trans "Dashboard" %}{% endblock %}

{% block maincontent %}
<div style="width: 350px; height: 300px">
CONTENT DASHBOARD
{% autoescape off %}
    {{ img }}
{% endautoescape %}
</div>
{% endblock %}

md/templates/md/lists.html
{% extends 'md_base.html' %}

{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block pagetitle %} {% trans "Lists" %}{% endblock %}

{% block maincontent %}
<div style="width: 350px; height: 300px">
LISTS
{% autoescape off %}
    {{ img }}
{% endautoescape %}
</div>
{% endblock %}

{% block external_js %}
    <script src="{% static 'md/md.js' %}"></script>
{% endblock %}

md/templates/md/navigation.html
{% load url from future %}
{% load i18n %}

<div class="main_menu">
<ul>
    {% for mi in menu_items %}
        <li><a href="{{ mi.url }}" {% if mi.code == active_tab %} class="mn_selected" {% endif %}>{{ mi.name }}</a></li>
    {% endfor %}

    <li><a href={% url 'auth:logout' %}>{% trans 'Logout' %}</a></li>
</ul>

</div>

</div>

md/templates/md/templates.html
{% extends 'md_base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load url from future %}

{% block pagetitle %} {% trans "Lists" %}{% endblock %}


{% block external_js %}
    <script src="{% static 'js/templates.js' %}" type="text/javascript"></script>
{% endblock %}

{% block maincontent %}
<div class="tabs_container">
	<div data-dojo-type="dijit/layout/BorderContainer" title="{% trans 'Templates' %}" id="templates_container">
		<div data-dojo-type="dijit/layout/AccordionContainer" data-dojo-props="region:'leading'" style="width:40%">
			<div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'Template List' %}" selected="true">
				<div id="templates_list_grid"></div>
				<div id="templates_msg"></div>
			</div>
			<div data-dojo-type="dijit/layout/ContentPane" title="{% trans 'Image Manager' %}" id="image_manager_pane">
				<div id="templates_fmg"></div>
			</div>
		</div>

		<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'">
			<div>{% include 'md/forms/templates_addedit.html' %}</div>
		</div>

	</div>
</div>

{% endblock %}